import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: "#E8F6E9",
  },
  root: {
    flex: 1,
    backgroundColor: "#E8F6E9",
  },
  scrollContent: {
    paddingHorizontal: 16,
    paddingBottom: 20,
  },
  header: {
    paddingHorizontal: 16,
    paddingVertical: 10,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  backButton: {
    width: 32,
    height: 32,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: "#065f46",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#064e3b",
  },
  headerTitle: {
    color: "#000000ff",
    fontSize: 18,
    fontWeight: "600",
  },
  imageCard: {
    marginTop: 4,
    backgroundColor: "#064e3b",
    borderRadius: 18,
    padding: 10,
    alignItems: "center",
  },
  leafImage: {
    width: "100%",
    height: 260,
    borderRadius: 14,
  },
  imageLabel: {
    marginTop: 8,
    color: "#ffffffff",
    fontSize: 13,
  },
  section: {
    marginTop: 18,
  },
  sectionTitle: {
    color: "#000000ff",
    fontSize: 16,
    fontWeight: "600",
    marginBottom: 10,
  },
  featureCard: {
    backgroundColor: "#629181",
    borderRadius: 16,
    paddingHorizontal: 14,
    paddingVertical: 12,
    marginBottom: 10,
    borderWidth: 1,
    borderColor: "#629181",
  },
  featureHeaderRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginBottom: 4,
  },
  featureTitle: {
    color: "#ffffffff",
    fontSize: 16,
    fontWeight: "600",
  },
  featureText: {
    color: "#ffffffff",
    fontSize: 14,
    marginTop: 2,
  },
  featureValue: {
    fontWeight: "700",
    color: "#ffffffff",
  },
  featureHint: {
    color: "#ffffffff",
    fontSize: 12,
    marginTop: 4,
  },
  actionsRow: {
    flexDirection: "row",
    gap: 10,
    marginTop: 18,
    marginBottom: 10,
  },
  buttonHalf: {
    flex: 1,
  },
  mainButton: {
    backgroundColor: "#629181",
    borderRadius: 999,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 12,
    gap: 8,
  },
  mainButtonText: {
    color: "#ffffffff",
    fontSize: 15,
    fontWeight: "700",
  },
  secondaryButton: {
    backgroundColor: "#629181",
    borderRadius: 999,
    borderWidth: 1,
    borderColor: "#629181",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 12,
    gap: 8,
  },
  secondaryButtonText: {
    color: "#ffffffff",
    fontSize: 15,
    fontWeight: "600",
  },
  errorContainer: {
    flex: 1,
    backgroundColor: "#F6EFE5",
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 24,
    gap: 12,
  },
  errorText: {
    color: "#e5e7eb",
    fontSize: 14,
    textAlign: "center",
  },
});
