/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/analytics`; params?: Router.UnknownInputParams; } | { pathname: `/batches`; params?: Router.UnknownInputParams; } | { pathname: `/camera`; params?: Router.UnknownInputParams; } | { pathname: `/history`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/preview`; params?: Router.UnknownInputParams; } | { pathname: `/result`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/styles/analyticsStyles`; params?: Router.UnknownInputParams; } | { pathname: `/styles/batchAssignmentStyles`; params?: Router.UnknownInputParams; } | { pathname: `/styles/cameraCaptureStyles`; params?: Router.UnknownInputParams; } | { pathname: `/styles/historyStyles`; params?: Router.UnknownInputParams; } | { pathname: `/styles/homeDashboardStyles`; params?: Router.UnknownInputParams; } | { pathname: `/styles/predictionResultStyles`; params?: Router.UnknownInputParams; } | { pathname: `/styles/previewStyles`; params?: Router.UnknownInputParams; } | { pathname: `/styles/settingsStyles`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/analytics`; params?: Router.UnknownOutputParams; } | { pathname: `/batches`; params?: Router.UnknownOutputParams; } | { pathname: `/camera`; params?: Router.UnknownOutputParams; } | { pathname: `/history`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/preview`; params?: Router.UnknownOutputParams; } | { pathname: `/result`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/styles/analyticsStyles`; params?: Router.UnknownOutputParams; } | { pathname: `/styles/batchAssignmentStyles`; params?: Router.UnknownOutputParams; } | { pathname: `/styles/cameraCaptureStyles`; params?: Router.UnknownOutputParams; } | { pathname: `/styles/historyStyles`; params?: Router.UnknownOutputParams; } | { pathname: `/styles/homeDashboardStyles`; params?: Router.UnknownOutputParams; } | { pathname: `/styles/predictionResultStyles`; params?: Router.UnknownOutputParams; } | { pathname: `/styles/previewStyles`; params?: Router.UnknownOutputParams; } | { pathname: `/styles/settingsStyles`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/analytics${`?${string}` | `#${string}` | ''}` | `/batches${`?${string}` | `#${string}` | ''}` | `/camera${`?${string}` | `#${string}` | ''}` | `/history${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/preview${`?${string}` | `#${string}` | ''}` | `/result${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/styles/analyticsStyles${`?${string}` | `#${string}` | ''}` | `/styles/batchAssignmentStyles${`?${string}` | `#${string}` | ''}` | `/styles/cameraCaptureStyles${`?${string}` | `#${string}` | ''}` | `/styles/historyStyles${`?${string}` | `#${string}` | ''}` | `/styles/homeDashboardStyles${`?${string}` | `#${string}` | ''}` | `/styles/predictionResultStyles${`?${string}` | `#${string}` | ''}` | `/styles/previewStyles${`?${string}` | `#${string}` | ''}` | `/styles/settingsStyles${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/analytics`; params?: Router.UnknownInputParams; } | { pathname: `/batches`; params?: Router.UnknownInputParams; } | { pathname: `/camera`; params?: Router.UnknownInputParams; } | { pathname: `/history`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/preview`; params?: Router.UnknownInputParams; } | { pathname: `/result`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/styles/analyticsStyles`; params?: Router.UnknownInputParams; } | { pathname: `/styles/batchAssignmentStyles`; params?: Router.UnknownInputParams; } | { pathname: `/styles/cameraCaptureStyles`; params?: Router.UnknownInputParams; } | { pathname: `/styles/historyStyles`; params?: Router.UnknownInputParams; } | { pathname: `/styles/homeDashboardStyles`; params?: Router.UnknownInputParams; } | { pathname: `/styles/predictionResultStyles`; params?: Router.UnknownInputParams; } | { pathname: `/styles/previewStyles`; params?: Router.UnknownInputParams; } | { pathname: `/styles/settingsStyles`; params?: Router.UnknownInputParams; };
    }
  }
}
